version: '3'
services:
  webapp:
    build: ./webapp
    ports:
      - "8080:8080"

  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"

